### ISSUE TITLE
An error occurred while installing pibidav: Default value for naming_series must be in the list of options.

### ISSUE THREAD

**Issue by samjaninf** [pibico/pibiDAV#16]
Not sure why this is happening.

I have frappe version 14.42.0
and erpnext version: 14.32.1

```
Installing pibidav...                                                                                                                                                                       Updating DocTypes for pibidav       : [========================================] 100%                                                                                                       An error occurred while installing pibidav: Default value for naming_series must be in the list of options.                                                                                 Traceback (most recent call last):                                                                                                                                                            File "apps/frappe/frappe/commands/site.py", line 415, in install_app                                                                                                                          _install_app(app, verbose=context.verbose, force=force)                                                                                                                                   File "apps/frappe/frappe/installer.py", line 313, in install_app                                                                                                                              sync_fixtures(name)                                                                                                                                                                       File "apps/frappe/frappe/utils/fixtures.py", line 21, in sync_fixtures                                                                                                                        import_fixtures(app)                                                                                                                                                                      File "apps/frappe/frappe/utils/fixtures.py", line 40, in import_fixtures                                                                                                                      import_doc(file_path)                                                                                                                                                                     File "apps/frappe/frappe/core/doctype/data_import/data_import.py", line 216, in import_doc                                                                                                    import_file_by_path(                                                                                                                                                                      File "apps/frappe/frappe/modules/import_file.py", line 145, in import_file_by_path                                                                                                            import_doc(                                                                                                                                                                               File "apps/frappe/frappe/modules/import_file.py", line 242, in import_doc
    doc.insert()
  File "apps/frappe/frappe/model/document.py", line 285, in insert
    self.run_post_save_methods()
  File "apps/frappe/frappe/model/document.py", line 1082, in run_post_save_methods
    self.run_method("on_update")                                                                                                                                                              File "apps/frappe/frappe/model/document.py", line 914, in run_method                                                                                                                          out = Document.hook(fn)(self, *args, **kwargs)                                                                                                                                            File "apps/frappe/frappe/model/document.py", line 1267, in composer                                                                                                                           return composed(self, method, *args, **kwargs)                                                                                                                                            File "apps/frappe/frappe/model/document.py", line 1249, in runner                                                                                                                             add_to_return_value(self, fn(self, *args, **kwargs))                                                                                                                                      File "apps/frappe/frappe/model/document.py", line 911, in fn                                                                                                                                  return method_object(*args, **kwargs)
  File "apps/frappe/frappe/custom/doctype/custom_field/custom_field.py", line 102, in on_update
    validate_fields_for_doctype(self.dt)                                                                                                                                                      File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1037, in validate_fields_for_doctype                                                                                          validate_fields(meta)                                                                                                                                                                     File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1472, in validate_fields                                                                                                      check_illegal_default(d)                                                                                                                                                                  File "apps/frappe/frappe/core/doctype/doctype/doctype.py", line 1186, in check_illegal_default                                                                                                frappe.throw(                                                                                                                                                                             File "apps/frappe/frappe/__init__.py", line 533, in throw                                                                                                                                     msgprint(                                                                                                                                                                                 File "apps/frappe/frappe/__init__.py", line 501, in msgprint                                                                                                                                  _raise_exception()                                                                                                                                                                        File "apps/frappe/frappe/__init__.py", line 450, in _raise_exception                                                                                                                          raise raise_exception(msg)                                                                                                                                                              frappe.exceptions.ValidationError: Default value for naming_series must be in the list of options.
```

**Comment by pibico** [comment]
According the instructions

**Compatibility**
PibiDAV has been tested on Frappe/ERPNext version-13 only.

On versions above version-13 there could be issues not identified.
